phpspec 5.0 support
leanphp/phpspec-code-coverage pull request #35
Opened 2018-07-02 18:07 UTC by samsonasik

2018-07-15 18:56 UTC, msvrtan commented
Any change @ek9 of merging this in + new release? phpspec 5.0 was released yesterday

2018-07-16 09:24 UTC, sp-felix-carmona requested changes

2018-07-16 09:24 UTC, sp-felix-carmona commented on composer.json
> +        "phpspec/phpspec": "^4.2|^5.0",
it should be `||` instead of `|`

2018-07-16 09:27 UTC, samsonasik commented on composer.json
> +        "phpspec/phpspec": "^4.2|^5.0",
updated

2018-08-06 15:27 UTC, roukmoute commented
Any news about that?

2018-08-06 16:16 UTC, samsonasik commented
@roukmoute temporary workaround until it get merged, we can define in composer.json my repository fork:

```json
    "require-dev": {
        // ...
        "leanphp/phpspec-code-coverage": "dev-patch-1"
        // ...
    },
    "repositories" : [
        {
            "type" : "vcs",
            "url" : "https://github.com/samsonasik/phpspec-code-coverage",
            "no-api": true
        }
    ]
```

2018-08-06 16:17 UTC, roukmoute commented
Yep thanks, this is what I've done.

2018-08-14 12:14 UTC, roukmoute commented
@samsonasik I think you could do a temporary valid packagist waiting for it to unlock here.

2018-10-22 10:07 UTC, bartosz-maciaszek commented
Any news on this?

2019-01-08 09:28 UTC, UFOMelkor approved these changes

2019-01-15 16:35 UTC, danmichaelo commented
The PR seems valid. According to the [phpspec changelog](https://github.com/phpspec/phpspec/blob/master/CHANGES-v5.md) there shouldn't be any BC breaks apart the PHP version bump.

But @ek9 hasn't been active on github since July 2018, so I guess there's isn't much hope of having this accepted soon. That's quite a long github break btw., I really hope everything is fine with him/her!

2019-02-20 11:11 UTC, rlanting commented
The domain ek9.co seems to have expired 2018-10, which makes me think nothing will happen here. The only other person I see in the commit history is @Seldaek, so perhaps he can shed some light on what is going on.

2019-02-20 11:21 UTC, Seldaek commented
Sorry but I have no idea what this project even is, I merely submitted a PR to remove a link because I got a warning for it on packagist.org support.

2019-02-20 12:04 UTC, loevgaard commented
@sp-felix-carmona or @UFOMelkor do you have write access? It seems @ek9 is rather inactive

2019-02-22 05:55 UTC, Dragonrun1 commented
So if anyone else is interested I decided to fork this and add my fork to Packagist. I updated it for ^5.0 as well so at least until this one comes back to life you are all welcome to use it.
composer require dragonrun1/phpspec-code-coverage

2019-02-23 14:17 UTC, aur1mas commented
@Dragonrun1 if you're planning to maintain this bundle, consider tagging new version (to make it stable) & allowing to submit issues ;)

2019-02-23 19:34 UTC, Dragonrun1 commented
I don't have a lot of time to do any real package maintenance but since I do use it a lot I thought I'd try to help some other people out a little while I was at it. I'll look at doing a new tagged version in next couple days and if people have PRs I'll look at them as well as I have time. I've got a lot of other projects going right now so I wasn't looking at adding a new one ;)

2019-03-05 12:01 UTC, shulard commented
Hello @Dragonrun1 !

It's really cool to have published a new packagist version. Since you haven't enough time to work on that lib, what do you think to move it under an organization with multiple maintainer in it ? It'll just allow to have more people behind the lib and avoid the same issue that we had on this one :smile:.

Personnaly, I can take some time to maintain this one.

2019-03-05 17:37 UTC, Dragonrun1 commented
@shulard 
Sounds like a great idea if you want to make one and add me to it that would work or I could but I'd like some input on what to call the group etc. and it might be a little while before I can make the change.

2019-03-05 18:10 UTC, jaylinski commented
@shulard @Dragonrun1 I thought about using the existing phpspec organization for maintaining this package. See https://github.com/phpspec/phpspec/pull/1245.

If the phpspec-maintainers are willing to take this repository in, we wouldn't have to create a separate organization. Otherwise the plan with the organization seems like a good idea. :+1:

2019-03-06 15:37 UTC, shulard commented
Hello @jaylinski !

You're absolutely right, if we can move that repository in the main phpspec organization, it'll help a lot. Let see what they think about it.

2019-03-06 15:37 UTC, shulard commented
Hello @jaylinski !

You're absolutely right, if we can move that repository in the main phpspec organization, it'll help a lot. Let see what they think about it.

2019-04-16 21:56 UTC, jaylinski commented
> Hello @jaylinski !
> 
> You're absolutely right, if we can move that repository in the main phpspec organization, it'll help a lot. Let see what they think about it.

Seems they are inactive too... :roll_eyes:

2019-06-12 08:32 UTC, BigZ commented
please ! we need this one !

2019-06-14 13:40 UTC, LewisMcFly commented
Any update? We need it as well.

2019-06-15 16:14 UTC, mamazu commented
Well the build job is failing. So we might need to fix that first.

2019-06-15 16:22 UTC, samsonasik commented
The travis build failure in php 7.2 env is nothing todo with the changes. It was travis issue.

2019-06-15 16:24 UTC, mamazu commented
Ah then they need to restart the job.

2019-06-28 07:23 UTC, jaylinski commented
> Hello @jaylinski !
> 
> You're absolutely right, if we can move that repository in the main phpspec organization, it'll help a lot. Let see what they think about it.

Turns out they don't like the idea...

2019-07-01 23:57 UTC, Dragonrun1 approved these changes

2019-07-01 23:59 UTC, Dragonrun1 commented
Sorry I've been busy with school etc but finally, have a little time to try to move at least the merge forward.

2019-07-02 00:16 UTC, Dragonrun1 commented
Sorry thought this was on my fork guess not but while I'm here if there are any other ideas on improving the project I might have a little time right now to look into working on some stuff so ideas are welcome.

2019-07-04 12:44 UTC, drupol commented
Based on #38 , there is now a fork that support PHPSpec 5: https://packagist.org/packages/drupol/phpspec-code-coverage

2019-08-27 16:19 UTC, BigZ commented
as phpspec doesn't want it and the maintainer is away from github since more than a year, i think it is time for this library to find a new home.
any one with solid maintaining capabilities willing to take this one ?

2019-08-28 08:47 UTC, shulard commented
I’l not sure about solid maintaining capabilities but I’ll be glad to help ;-)

To avoid the same issue with the only commiter/owner who left the project, I think the best is to create an organisation like phpspec-extension. Maybe we’ll have the chance to aggregate multiple extension maintainers in it...

WDYT ?
I already created the org and forked the project in it. Anyone who want to be involved in that project can be added...

2019-08-28 08:53 UTC, drupol commented
I'll be glad to help maintaining the fork I did.

2019-08-28 08:59 UTC, shulard commented
@drupol thank you for the fork but what do you think about the organisation ? Because it’s always better to not rely on individuals directly for such things...

Won’t it be better to add you as a maintainer on the org repo ?

2019-08-28 09:00 UTC, shulard commented
Also for the communication and share relying on the phpspec-extensions name can be clearer and help being more confident with the support...

2019-08-28 09:03 UTC, drupol commented
> @drupol thank you for the fork but what do you think about the organisation ? Because it’s always better to not rely on individuals directly for such things...
> 
> Won’t it be better to add you as a maintainer on the org repo ?

Definitely. I'll be glad to do so. 
However, i'm abroad right now with limited access to the Internet, so, we'll discuss this further in a week :)

2019-08-28 09:11 UTC, bartosz-maciaszek commented
`friends-of-phpspec` ;) I'm also happy to help.

2019-08-28 09:12 UTC, shulard commented
Glad to hear this and yes the org name can be updated :-)

Same on my side limited access to the web until Friday but we’ll discuss this ASAP.

2019-08-28 15:16 UTC, jaylinski commented
@shulard Thanks for taking the lead on this. I'm also happy to help as a org maintainer.

2019-08-30 08:35 UTC, shulard commented
Hello guys !

Little update, the org was renamed `friends-of-phpspec` and the master branch for the fork was updated to reflect the @drupol version.

You can visit the org here: https://github.com/friends-of-phpspec

@drupol, @jaylinski you have been added as member of the org and you have access to the repository. I'll create some issues / PR to be sure that everything will be migrated.

2019-10-01 13:13 UTC, shulard commented
Hello everyone !

I'm glad to announce that I've just published a new official release of this package from the new [friends of PHPSpec](https://github.com/friends-of-phpspec) organization !

If you want a revamped and maintained version (compatible with PHPSpec 5.0), update your composer.json and move forward 😉.

https://packagist.org/packages/friends-of-phpspec/phpspec-code-coverage

Currently, everything is compatible so a quick composer.json update will make it works smoothly...

2019-10-01 13:14 UTC, samsonasik commented
@shulard thank you, I can close it ;)

2019-10-01 13:14 UTC, closed without merging

2019-10-01 13:32 UTC, shulard commented
@Dragonrun1, if you still don't want to maintain your own release of this package, can you mark it abandoned on packagist in favor of the new one ?

2019-10-02 17:16 UTC, Dragonrun1 commented
I'll look at updating my fork today.